### ISSUE TITLE
Issue with Image Retrieval from data.json

### ISSUE THREAD

**Issue by Vimal-Mudalagi** [darrk-heart/SpaceVoyageHub#1]
Hi! 
I noticed in your README.md that you're facing an issue with retrieving images from the data.json file. I’d love to help fix this problem by ensuring the images are displayed properly in the app. Could you please assign me to this issue?

Thank you.

**Comment by 1skepta** [comment]
yes, for sure

**Comment by 1skepta** [comment]
Thanks for offering to help! I've assigned you to the issue. Please go ahead and fork the repo, make the changes, and submit a PR

**Comment by Vimal-Mudalagi** [comment]
Thanks! 
I'll get started and submit a PR soon.

**Comment by 1skepta** [comment]
you know what i've added you as a contributor on the repo as well so you can make direct changes

**Comment by Vimal-Mudalagi** [comment]
I appreciate it and will make the changes when I can.

**Comment by Vimal-Mudalagi** [comment]
Hi!
I submitted a PR to fix the image retrieval issue from data.json. Please check it out when you can.

**Comment by 1skepta** [comment]
yayyy!! it worked thanks a million

**Comment by Vimal-Mudalagi** [comment]
great to hear. happy to contribute!

**Comment by Vimal-Mudalagi** [comment]
If you need any help in the future, feel free to reach out.
